---
- name: 获取ca.crt base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/ca.crt"
  register: ca_cert_base64

- name: 获取kube-controller-manager.crt base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/kube-controller-manager.crt"
  register: kube_controller_manager_cert_base64

- name: 获取kube-controller-manager.key base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/kube-controller-manager.key"
  register: kube_controller_manager_key_base64

- name: 获取kube-scheduler.crt base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/kube-scheduler.crt"
  register: kube_scheduler_cert_base64

- name: 获取kube-scheduler.key base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/kube-scheduler.key"
  register: kube_scheduler_key_base64

- name: 获取admin.crt base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/admin.crt"
  register: admin_cert_base64

- name: 获取admin.key base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/admin.key"
  register: admin_key_base64

- name: 获取kube-proxy.crt base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/kube-proxy.crt"
  register: kube_proxy_cert_base64

- name: 获取kube-proxy.key base64编码
  slurp:
    src: "{{ localhost_dir }}/pki/kube-proxy.key"
  register: kube_proxy_key_base64

- name: 生成 kube-controller-manager、kube-scheduler、admin、kube-proxy kubeconfig 文件
  template:
    src: "{{ item }}.j2"
    dest: "{{ localhost_dir }}/conf/{{ item }}"
    mode: 0600
  with_items:
    - controller-manager.kubeconf
    - scheduler.kubeconf
    - admin.kubeconf
    - kube-proxy.kubeconf
