---
- name: 获取ca.crt base64编码
  slurp:
    src: "{{ playbook_dir }}/pki/ca.crt"
  register: ca_cert_base64

- name: 获取kube-controller-manager.crt base64编码
  slurp:
    src: "{{ playbook_dir }}/pki/kube-controller-manager.crt"
  register: kube_controller_manager_cert_base64

- name: 获取kube-controller-manager.key base64编码
  slurp:
    src: "{{ playbook_dir }}/pki/kube-controller-manager.key"
  register: kube_controller_manager_key_base64

- name: 获取kube-scheduler.crt base64编码
  slurp:
    src: "{{ playbook_dir }}/pki/kube-scheduler.crt"
  register: kube_scheduler_cert_base64

- name: 获取kube-scheduler.key base64编码
  slurp:
    src: "{{ playbook_dir }}/pki/kube-scheduler.key"
  register: kube_scheduler_key_base64

- name: 生成 kube-controller-manager、kube-scheduler kubeconfig 文件
  template:
    src: "{{ item }}.j2"
    dest: "{{ playbook_dir }}/pki/{{ item }}"
    mode: 0600
  with_items:
    - controller-manager.conf
    - scheduler.conf
