---
- name: 创建k8s pki 本地文件目录
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ localhost_dir }}/pki"
    - "{{ localhost_dir }}/conf"

- name: 拷贝 k8s-csr.conf 
  copy:
    src: k8s-csr.conf
    dest: "{{ localhost_dir }}/pki/k8s-csr.conf"
    mode: 0600

- import_tasks: gen-cert.yml

- import_tasks: kubeconfig.yml
