---
- name: 创建 ansible 本地文件目录
  file:
    path: "{{ item }}"
    state: directory
  with_items:
   - "{{ localhost_dir }}/files/etcd-{{ etcd_ver }}"
   - "{{ localhost_dir }}/files/k8s-{{ kube_ver }}"
   - "{{ localhost_dir }}/files/docker-{{ docker_ver }}"
   - "{{ localhost_dir }}/files/cni-plugins-{{ cni_ver }}"

- import_tasks: docker.yml

- import_tasks: etcd.yml

- import_tasks: k8s.yml

- import_tasks: cni.yml
