---
- name: 在 /etc/fstab 移除 swap 分区开机挂载 
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: 检查是否开启swap
  command: /sbin/swapon -s
  register: swapon
  changed_when: no

- name: 关闭swap
  command: /sbin/swapoff -a
  when: swapon.stdout