---
- name: 拷贝flannel.yml到第一台master
  template:
    src: flannel.yml.j2
    dest: "{{ kube_dir }}/flannel.yml"
  delegate_to: "{{ groups['kube-master']|first }}"
  run_once: true

- name: 部署 flannel
  shell: |
    {{ kube_bin_dir }}/kubectl apply -f {{ kube_dir }}/flannel.yml
  delegate_to: "{{ groups['kube-master']|first }}"
  run_once: true
