# k8s集群相关变量

# k8s版本
kube_ver: v1.15.0

# pod IP段
cluster_CIDR: 10.244.0.0/16
# svc IP段
service_CIDR: 10.96.0.0/12
# 集群网络apiserver地址，通常取svc开通第一个
cluster_service_IP: 10.96.0.1
# 集群DNS地址
cluster_dns_IP: 10.96.0.10
# nodeport端口范围
service_node_port_range: "30000-32767"

# k8s安装目录
kube_bin_dir: /usr/local/bin
# cni安装目录
cni_bin_dir: /opt/cni/bin
# 静态pod配置目录
pod_manifests_dir: /etc/kubernetes/manifests
# k8s配置目录
kube_dir: /etc/kubernetes
# nginx-proxy配置目录
nginx_proxy_dir: /etc/kubernetes/nginx

# kube-proxy 模式 iptables、ipvs
kube_proxy_mode: ipvs

# nginx-proxy 检查检查端口
nginx_proxy_healthcheck_port: 8089
# nginx-proxy 服务端口
nginx_proxy_port: 8443

# master 节点打污点
master_taint: true

# DNS 配置
# https://github.com/coredns/coredns/tree/master/plugin/loop
# ansible部署时会检测/etc/resolv.conf是否存在"nameserver 127.0.0.53"，如果存在将会把kubelet的resolvConf配置为/run/systemd/resolve/resolv.conf
# 默认使用resolv_conf的值作为kubelet的resolvConf配置
resolv_conf: /etc/resolv.conf
