---
- block:
    - name: 添加docker安装源key
      apt_key:
        url: "{{ docker_repo_base_url }}/{{ ansible_distribution|lower }}/gpg"
        state: present

    - name: 添加 docker apt安装源
      apt_repository:
        repo: >-
          deb {{ docker_repo_base_url }}/{{ ansible_distribution|lower }}
          {{ ansible_distribution_release|lower }}
          stable
        state: present
        filename: docker-ce

    - name: 安装 containerd (apt)
      package:
        name: containerd
        state: present
      notify: restart docker
  when: ansible_os_family == "Debian"

- block:
    - name: 添加 docker yum 源
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        file: docker-ce
        baseurl: "{{ docker_repo_base_url }}/{{ ansible_distribution|lower }}/7/$basearch/stable"
        gpgkey: "{{ docker_repo_base_url }}/{{ ansible_distribution|lower }}/gpg"
        enabled: yes
        gpgcheck: yes

    - name: 安装 containerd (yum)
      yum:
        name: containerd
        state: present
      notify: restart docker
  when: ansible_os_family == "RedHat"
