---
- name: 创建 containerd 配置目录
  file:
    path: /etc/containerd
    state: directory

- import_tasks: ../../k8s/sys-setup/tasks/sysctl.yml

- include_tasks: containerd_bin.yml
  when: containerd_install == "bin"

- include_tasks: containerd_repo.yml
  when: containerd_install == "repo"

- name: 分发 containerd 配置文件
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify: restart containerd

- name: 分发 crictl 配置文件
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
