---
- name: 清理所有docker容器
  shell: "{{ docker_bin_dir }}/docker ps -aq | xargs -r docker rm -fv"
  register: remove_all_containers
  retries: 4
  until: remove_all_containers.rc == 0
  delay: 5

- name: 停止 docker
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - docker
    - containerd
  failed_when: false
  when: reset_cri | bool

- name: 清理容器运行时 services 文件
  file:
    path: "/etc/systemd/system/{{ item }}.service"
    state: absent
  with_items:
    - docker
    - containerd
  when: 
    - reset_cri | bool

- name: 卸载 docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent
  ignore_errors: yes
  when: 
    - reset_cri | bool
    - docker_install == "repo"

- name: 检查 docker0 网桥
  stat:
    path: /sys/class/net/docker0
  register: docker0

- name: 移除 docker0 网桥
  shell: ip link del docker0
  when: docker0.stat.exists
