---
- name: 创建 k8s 证书目录、配置目录
  file:
    path: "{{ item }}"
    state: directory
  with_items:
   - "{{ kube_dir }}/pki"
   - "{{ kube_dir }}"
   - ~/.kube

- name: 分发 kube-controller-manager、kube-scheduler kubeconfig 文件
  copy:
    src: "{{ localhost_dir }}/conf/{{ item }}"
    dest: "{{ kube_dir }}/{{ item }}"
    mode: 0600
  with_items:
    - controller-manager.kubeconf
    - scheduler.kubeconf

- name: 分发 admin kubeconfig 文件
  copy:
    src: "{{ localhost_dir }}/conf/admin.kubeconf"
    dest: ~/.kube/config
    mode: 0600

- name: 分发 kube-apiserver、kube-controller-manager、kube-scheduler service 文件
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service

- name: 分发 kube-apiserver、kube-controller-manager、kube-scheduler、kubectl 二进制文件
  copy:
    src: "{{ localhost_dir }}/files/k8s-{{ kube_ver }}/{{ item }}"
    dest: "{{ kube_bin_dir }}/{{ item }}"
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kubectl

- name: 分发 k8s apiserver 证书 
  copy:
    src: "{{ localhost_dir }}/pki/{{ item }}"
    dest: "{{ kube_dir }}/pki/{{ item }}"
    mode: 0600
  with_items:
   - ca.crt
   - ca.key
   - "apiserver-{{ master_name }}.crt"
   - "apiserver-{{ master_name }}.key"
   - apiserver-etcd-client.crt
   - apiserver-etcd-client.key
   - apiserver-kubelet-client.crt
   - apiserver-kubelet-client.key
   - front-proxy-ca.crt
   - front-proxy-ca.key
   - front-proxy-client.crt
   - front-proxy-client.key
   - sa.pub
   - sa.key

- name: 设置开机启动 kube-apiserver、kube-controller-manager、kube-scheduler
  systemd:
    name: "{{ item }}"
    enabled: yes 
    daemon_reload: yes
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: 启动 kube-apiserver、kube-controller-manager、kube-scheduler
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
