---
- name: 创建 k8s 证书目录、配置目录
  file:
    path: "{{ item }}"
    state: directory
  with_items:
   - /etc/kubernetes/pki
   - /etc/kubernetes

- name: 分发 kube-controller-manager、kube-scheduler kubeconfig 文件
  copy:
    src: "{{ playbook_dir }}/pki/{{ item }}"
    dest: "/etc/kubernetes/{{ item }}"
    mode: 0600
  with_items:
    - controller-manager.conf
    - scheduler.conf

- name: 分发 kube-apiserver、kube-controller-manager、kube-scheduler service 文件
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service

- name: 分发 kube-apiserver、kube-controller-manager、kube-scheduler 二进制文件
  copy:
    src: "{{ playbook_dir }}/files/k8s-{{ kube_ver }}/{{ item }}"
    dest: "{{ kube_bin_dir }}/{{ item }}"
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: 分发 k8s apiserver 证书 
  copy:
    src: "{{ playbook_dir }}/pki/{{ item }}"
    dest: "/etc/kubernetes/pki/{{ item }}"
    mode: 0600
  with_items:
   - ca.crt
   - ca.key
   - "apiserver-{{ master_name }}.crt"
   - "apiserver-{{ master_name }}.crt.key"
   - apiserver-etcd-client.crt
   - apiserver-etcd-client.key
   - apiserver-kubelet-client.crt
   - apiserver-kubelet-client.key
   - front-proxy-ca.crt
   - front-proxy-ca.key
   - front-proxy-client.crt
   - front-proxy-client.key
   - sa.pub
   - sa.key