---
- name: 创建 kube-proxy 配置目录
  file:
    path: "{{ item }}"
    state: directory
  with_items:
   - "{{ kube_dir }}"

- name: 分发 kube-proxy kubeconfig 配置
  template:
    src: "{{ localhost_dir }}/conf/kube-proxy.kubeconf"
    dest: "{{ kube_dir }}/kube-proxy.kubeconf"
    mode: 0644

- name: 更改 kube-proxy kubeconfig apiserver地址信息
  replace:
    path: "{{ kube_dir }}/kube-proxy.kubeconf"
    regexp: '6443'
    replace: "{{ nginx_proxy_port | string }}"
  when: inventory_hostname not in groups['kube-master']

- name: 分发 kube-proxy 配置文件
  template:
    src: kube-proxy-config.yaml.j2
    dest: "{{ kube_dir }}/kube-proxy-config.yaml"
    mode: 0644

- name: 分发 kube-proxy service 文件
  template:
    src: "kube-proxy.service.j2"
    dest: "/etc/systemd/system/kube-proxy.service"
    mode: 0644

- name: 分发 kube-proxy 二进制 文件
  copy:
    src: "{{ localhost_dir }}/files/k8s-{{ kube_ver }}/kube-proxy"
    dest: "{{ kube_bin_dir }}/kube-proxy"
    mode: 755

- name: 启动 kube-proxy
  systemd:
    name: kube-proxy
    enabled: yes 
    daemon_reload: yes
    state: restarted
