---
- name: 创建 CNI 插件目录、kubelet配置目录
  file:
    path: "{{ item }}"
    state: directory
  with_items:
   - "{{ cni_bin_dir }}"
   - "{{ kube_dir }}"
   - "{{ kube_dir }}/pki"
   - /var/lib/kubelet

- name: 分发 cni 组件
  unarchive:
    src: "{{ localhost_dir }}/files/cni-plugins-linux-amd64-{{ cni_ver }}.tgz"
    dest: "{{ cni_bin_dir }}"

- name: 分发 kubelet service 文件
  template:
    src: "kubelet.service.j2"
    dest: "/etc/systemd/system/kubelet.service"
    mode: 0644

- name: 分发 bootstrap-kubelet.conf 文件
  template:
    src: "bootstrap-kubelet.conf.j2"
    dest: "{{ kube_dir }}/bootstrap-kubelet.conf"
    mode: 0644

- name: 分发 ca.crt
  template:
    src: "{{ localhost_dir }}/pki/ca.crt"
    dest: "{{ kube_dir }}/pki/ca.crt"
    mode: 0600

- name: 分发 kubelet confing 文件
  template:
    src: kubelet-config.yaml.j2
    dest: "{{ kube_dir }}/kubelet-config.yaml"
    mode: 0644

- name: 分发 kubelet二进制 文件
  copy:
    src: "{{ localhost_dir }}/files/k8s-{{ kube_ver }}/kubelet"
    dest: "{{ kube_bin_dir }}/kubelet"
    mode: 755

- name: 启动 kubelet
  systemd:
    name: kubelet
    enabled: yes 
    daemon_reload: yes
    state: restarted
