---
- name: 创建 静态 pod 配置目录
  file:
    path: /etc/kubernetes/manifests
    state: directory
    mode: 0755

- import_tasks: tls-bootstrap.yml

- import_tasks: nginx.yml

- import_tasks: kubelet.yml

- import_tasks: kube-proxy.yml
