---
- name: 创建静态 pod 配置目录
  file:
    path: "{{ pod_manifests_dir }}"
    state: directory
    mode: 0755

- import_tasks: tls-bootstrap.yml

- import_tasks: nginx.yml

- import_tasks: check_resolv.yml

- import_tasks: kubelet.yml

- import_tasks: kube-proxy.yml
