---
- block:
    - name: 创建 nginx proxy 文件目录
      file:
        path: /etc/kubernetes/nginx
        state: directory
        owner: root
        mode: 0700

    - name: 分发 nginx proxy 配置
      template:
        src: nginx.conf.j2
        dest: /etc/kubernetes/nginx/nginx.conf
        owner: root
        mode: 0600

    - name: 分发 nginx proxy 静态pod启动文件
      template:
        src: nginx-proxy.yml.j2
        dest: /etc/kubernetes/manifests/nginx-proxy.yml

  when: inventory_hostname in groups['kube-node']
