---
- name: restart docker
  command: /bin/true
  notify:
    - docker | enable containerd
    - docker | enable docker
    - docker | reload systemd
    - docker | reload containerd
    - docker | reload docker
    - docker | wait for docker

- name: docker | enable containerd
  systemd:
    name: containerd
    enabled: yes
  when: not docker_ver_less_than_18_09 | bool

- name: docker | enable docker
  systemd:
    name: docker
    enabled: yes

- name: docker | reload systemd
  systemd:
    daemon_reload: yes

- name: docker | reload containerd
  systemd:
    name: containerd
    state: restarted
  when: not docker_ver_less_than_18_09 | bool

- name: docker | reload docker
  systemd:
    name: docker
    state: restarted

- name: docker | wait for docker
  command: "{% if docker_install == 'bin' %}{{ docker_bin_dir }}{% else %}/usr/bin{% endif %}/docker ps"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0
