---
- name: 分发 docker 二进制文件
  unarchive:
    src: "{{ localhost_dir }}/files/docker-{{ docker_ver }}.tgz"
    dest: "{{ docker_bin_dir }}"
    extra_opts:
    - --strip-components=1

- name: 创建 containerd.service 文件
  template:
    src: containerd.service.j2
    dest: /etc/systemd/system/containerd.service
  when: not docker_ver_less_than_18_09 | bool

- name: 创建 docker.service 文件
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
  notify: restart docker
