---
- name: 创建 docker 相关文件夹
  file:
    path: /etc/docker
    state: directory

- name: 复制 docker二进制文件到目标主机
  copy:
    src: "{{ local_dir }}/docker-{{ docker_ver }}/{{ item }}"
    dest: "{{ docker_bin_dir }}"
    mode: 0755
  with_items:
    - docker
    - docker-containerd
    - docker-containerd-ctr
    - docker-containerd-shim
    - dockerd
    - docker-init
    - docker-proxy
    - docker-runc

- name: 创建 docker.service 文件
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service

- name: systemd daemon_reload
  systemd:
    daemon_reload: yes

- name: 启动 docker
  systemd:
    state: started
    name: docker