---
- name: 创建 docker 相关文件夹
  file:
    path: /etc/docker
    state: directory

- include_tasks: docker_bin.yml
  when: docker_install == "bin"

- include_tasks: docker_repo.yml
  when: docker_install == "repo"
